a, b, c = map(float, input().split())
print(f'TRIANGULO: {0.5 * a * c:.3f}')
print(f'CIRCULO: {3.14159 * c * c:.3f}')
print(f'TRAPEZIO: {0.5 * (a + b) * c:.3f}')
print(f'QUADRADO: {b * b:.3f}')
print(f'RETANGULO: {a * b:.3f}')
